export interface GymMachineItem {
  id: string;
  name: string;
  nameEn?: string;
  category: "glutes_legs" | "cardio" | "back_upper" | "abs_core";
  categoryLabel: string;
  emoji: string;
  targetMuscles: string[];
  defaultMet: number; // MET для кардио
  intensityFactor: number; // Коэффициент нагрузки на сет
  defaultSets: number;
  defaultReps: number;
  defaultMinutes?: number;
  defaultWeightKg?: number;
  description: string;
  techniqueTip: string;
}

export const GYM_MACHINES: GymMachineItem[] = [
  // --- Ягодицы и ноги ---
  {
    id: "glute_bridge_bench",
    name: "Ягодичный мостик",
    nameEn: "Hip Thrust / Glute Bridge",
    category: "glutes_legs",
    categoryLabel: "Ягодицы и бёдра",
    emoji: "🍑",
    targetMuscles: ["Большая ягодичная", "Бицепс бедра"],
    defaultMet: 6.0,
    intensityFactor: 1.4,
    defaultSets: 4,
    defaultReps: 15,
    defaultWeightKg: 35,
    description: "Лучшее упражнение для формирования круглых и упругих ягодиц без перегрузки передней части бедра.",
    techniqueTip: "Упирайтесь лопатками в скамью, толкайте пятками, в верхней точке делайте паузу на 1–2 секунды и сжимайте ягодицы.",
  },
  {
    id: "leg_press",
    name: "Жим ногами в тренажере",
    nameEn: "Leg Press",
    category: "glutes_legs",
    categoryLabel: "Ягодицы и бёдра",
    emoji: "🦵",
    targetMuscles: ["Ягодицы", "Квадрицепсы", "Бицепс бедра"],
    defaultMet: 6.0,
    intensityFactor: 1.3,
    defaultSets: 4,
    defaultReps: 12,
    defaultWeightKg: 60,
    description: "Базовый тренажер для ног. Позволяет безопасно нагрузить ягодицы и бедра без осевой нагрузки на позвоночник.",
    techniqueTip: "Ставьте стопы ближе к верхнему краю платформы и чуть шире плеч для акцента на ягодицы. Не вставляйте колени в замок вверху.",
  },
  {
    id: "hack_squat",
    name: "Гакк-приседания",
    nameEn: "Hack Squat Machine",
    category: "glutes_legs",
    categoryLabel: "Ягодицы и бёдра",
    emoji: "🏋️‍♀️",
    targetMuscles: ["Квадрицепсы", "Ягодицы"],
    defaultMet: 6.5,
    intensityFactor: 1.4,
    defaultSets: 3,
    defaultReps: 12,
    description: "Тренажер с наклонной платформой и упором для спины для глубоких контролируемых приседаний.",
    techniqueTip: "Держите спину плотно прижатой к спинке, опускайтесь плавно до параллели или чуть глубже.",
  },
  {
    id: "hip_abduction",
    name: "Разведение ног сидя",
    nameEn: "Seated Hip Abductor",
    category: "glutes_legs",
    categoryLabel: "Ягодицы и бёдра",
    emoji: "✨",
    targetMuscles: ["Средняя ягодичная", "Малая ягодичная"],
    defaultMet: 4.5,
    intensityFactor: 1.0,
    defaultSets: 4,
    defaultReps: 20,
    description: "Тренажер для изоляции верхней и боковой части ягодиц («полочки»), формирует красивый силуэт бёдер.",
    techniqueTip: "Слегка наклоните корпус вперед и задерживайте колени в разведенном положении на секунду.",
  },
  {
    id: "lying_leg_curl",
    name: "Сгибание ног лёжа",
    nameEn: "Lying Leg Curl",
    category: "glutes_legs",
    categoryLabel: "Ягодицы и бёдра",
    emoji: "🎯",
    targetMuscles: ["Бицепс бедра (задняя поверхность)", "Икроножные"],
    defaultMet: 4.5,
    intensityFactor: 1.1,
    defaultSets: 3,
    defaultReps: 15,
    description: "Изолирующая проработка задней поверхности бедра, делает ножки подтянутыми сзади.",
    techniqueTip: "Не отрывайте таз от скамьи при сгибании, опускайте валик плавно без рывков.",
  },
  {
    id: "smith_machine_lunges",
    name: "Выпады в Смите",
    nameEn: "Smith Machine Lunges / Split Squat",
    category: "glutes_legs",
    categoryLabel: "Ягодицы и бёдра",
    emoji: "🔥",
    targetMuscles: ["Ягодицы", "Передняя поверхность бедра"],
    defaultMet: 6.0,
    intensityFactor: 1.3,
    defaultSets: 3,
    defaultReps: 12,
    description: "Болгарские выпады или выпады на месте с грифом тренажера Смита для максимальной устойчивости.",
    techniqueTip: "Сделайте широкий шаг, корпус слегка наклонен вперед над передней ногой для максимального растяжения ягодицы.",
  },

  // --- Кардио тренажеры ---
  {
    id: "treadmill_incline",
    name: "Беговая дорожка (ходьба в гору)",
    nameEn: "Incline Treadmill Walking",
    category: "cardio",
    categoryLabel: "Кардио",
    emoji: "🚶‍♀️",
    targetMuscles: ["Ягодицы", "Икры", "Сердечно-сосудистая система"],
    defaultMet: 7.0, // Высокий расход при угле 10-15% и скорости 5-6 км/ч
    intensityFactor: 1.0,
    defaultSets: 1,
    defaultReps: 1,
    defaultMinutes: 30,
    description: "Любимое кардио фитнес-моделей: наклон 10–12%, скорость 4.5–5.5 км/ч. Сжигает жир и отлично включает ягодицы!",
    techniqueTip: "Не держитесь за поручни руками — работайте руками вдоль тела, чтобы сжигать на 25% больше калорий.",
  },
  {
    id: "elliptical",
    name: "Эллиптический тренажер",
    nameEn: "Elliptical Trainer",
    category: "cardio",
    categoryLabel: "Кардио",
    emoji: "🏃‍♀️",
    targetMuscles: ["Все тело", "Бёдра", "Плечи"],
    defaultMet: 6.5,
    intensityFactor: 1.0,
    defaultSets: 1,
    defaultReps: 1,
    defaultMinutes: 25,
    description: "Мягкое кардио без ударной нагрузки на суставы и колени с одновременной работой ног и рук.",
    techniqueTip: "Давите пятками в педали и держите ровный темп дыхания.",
  },
  {
    id: "stairmaster",
    name: "Степпер / Тренажер-лестница",
    nameEn: "StairMaster / Step Climber",
    category: "cardio",
    categoryLabel: "Кардио",
    emoji: "🪜",
    targetMuscles: ["Ягодицы", "Икры", "Квадрицепсы"],
    defaultMet: 8.5,
    intensityFactor: 1.2,
    defaultSets: 1,
    defaultReps: 1,
    defaultMinutes: 20,
    description: "Один из самых энергозатратных кардиотренажеров в мире. Мощно прокачивает ягодицы при каждом шаге.",
    techniqueTip: "Ставьте всю стопу на ступеньку целиком и толкайтесь пяткой, сохраняя прямую осанку.",
  },
  {
    id: "stationary_bike",
    name: "Велотренажер",
    nameEn: "Stationary Exercise Bike",
    category: "cardio",
    categoryLabel: "Кардио",
    emoji: "🚴‍♀️",
    targetMuscles: ["Ноги", "Сердце"],
    defaultMet: 6.0,
    intensityFactor: 1.0,
    defaultSets: 1,
    defaultReps: 1,
    defaultMinutes: 30,
    description: "Классическое кардио для умеренного сжигания калорий и улучшения тонуса ног.",
    techniqueTip: "Отрегулируйте высоту сиденья так, чтобы нога в нижней точке педали была почти полностью выпрямлена.",
  },

  // --- Спина, плечи и верх тела ---
  {
    id: "lat_pulldown",
    name: "Тяга верхнего блока к груди",
    nameEn: "Lat Pulldown Machine",
    category: "back_upper",
    categoryLabel: "Спина и осанка",
    emoji: "🕊️",
    targetMuscles: ["Широчайшие мышцы спины", "Бицепсы", "Осанка"],
    defaultMet: 5.0,
    intensityFactor: 1.1,
    defaultSets: 3,
    defaultReps: 12,
    description: "Формирует красивую королевскую осанку и визуально сужает талию за счет аккуратного верха спины.",
    techniqueTip: "Тяните рукоять к верхней части груди, направляя локти вниз и слегка назад. Не раскачивайте корпус.",
  },
  {
    id: "seated_cable_row",
    name: "Тяга горизонтального блока",
    nameEn: "Seated Cable Row",
    category: "back_upper",
    categoryLabel: "Спина и осанка",
    emoji: "🚣‍♀️",
    targetMuscles: ["Середина спины", "Ромбовидные мышцы", "Задняя дельта"],
    defaultMet: 5.0,
    intensityFactor: 1.1,
    defaultSets: 3,
    defaultReps: 12,
    description: "Укрепляет мышечный корсет спины, снимает напряжение после сидячей работы за компьютером.",
    techniqueTip: "Сводите лопатки вместе в конце движения и держите плечи опущенными.",
  },
  {
    id: "hyperextension",
    name: "Гиперэкстензия",
    nameEn: "Hyperextension Bench",
    category: "back_upper",
    categoryLabel: "Спина и осанка",
    emoji: "🏹",
    targetMuscles: ["Ягодицы", "Поясница", "Бицепс бедра"],
    defaultMet: 5.0,
    intensityFactor: 1.2,
    defaultSets: 3,
    defaultReps: 15,
    description: "Универсальный тренажер: при круглой спине акцент идет на ягодицы, при прямой — на здоровье поясницы.",
    techniqueTip: "Для акцента на ягодицы округлите верх спины, разверните носки наружу и сжимайте ягодицы при подъеме.",
  },

  // --- Пресс и кор ---
  {
    id: "incline_situp_bench",
    name: "Скручивания на наклонной скамье",
    nameEn: "Incline Abdominal Bench",
    category: "abs_core",
    categoryLabel: "Пресс и талия",
    emoji: "🍫",
    targetMuscles: ["Прямая мышца живота", "Кор"],
    defaultMet: 5.0,
    intensityFactor: 1.0,
    defaultSets: 3,
    defaultReps: 15,
    description: "Эффективная проработка мышц пресса для подтянутого и плоского живота.",
    techniqueTip: "Не тяните себя за шею руками — скручивайте ребра к тазу на выдохе.",
  },
  {
    id: "plank",
    name: "Планка (статика)",
    nameEn: "Classic Plank",
    category: "abs_core",
    categoryLabel: "Пресс и талия",
    emoji: "⚡",
    targetMuscles: ["Глубокие мышцы кора", "Поперечная мышца живота"],
    defaultMet: 4.5,
    intensityFactor: 1.0,
    defaultSets: 3,
    defaultReps: 1,
    defaultMinutes: 1,
    description: "Укрепляет внутренний мышечный корсет, подтягивает живот и формирует осиную талию.",
    techniqueTip: "Держите тело в одну прямую линию от макушки до пяток, не провисайте в пояснице.",
  },
  {
    id: "leg_extension",
    name: "Разгибание ног сидя",
    nameEn: "Seated Leg Extension",
    category: "glutes_legs",
    categoryLabel: "Ягодицы и бёдра",
    emoji: "🦵",
    targetMuscles: ["Квадрицепсы"],
    defaultMet: 4.5,
    intensityFactor: 1.0,
    defaultSets: 3,
    defaultReps: 15,
    defaultWeightKg: 25,
    description: "Изолирующий тренажер для передней поверхности бедра, придает красивый рельеф ногам.",
    techniqueTip: "Плавно разгибайте ноги, задержитесь на 1 секунду вверху и медленно опускайте вес.",
  },
  {
    id: "hip_adduction",
    name: "Сведение ног сидя",
    nameEn: "Seated Hip Adductor",
    category: "glutes_legs",
    categoryLabel: "Ягодицы и бёдра",
    emoji: "🩰",
    targetMuscles: ["Приводящие мышцы бедра (внутренняя поверхность)"],
    defaultMet: 4.5,
    intensityFactor: 1.0,
    defaultSets: 3,
    defaultReps: 15,
    defaultWeightKg: 25,
    description: "Подтягивает внутреннюю поверхность бедра, формируя стройный и аккуратный контур ног.",
    techniqueTip: "Сводите ноги с контролем мышц, не ударяйте плитки тренажера друг о друга.",
  },
  {
    id: "pec_deck",
    name: "Тренажер «Бабочка» (Пек-дек)",
    nameEn: "Pec Deck / Butterfly Machine",
    category: "back_upper",
    categoryLabel: "Грудь и осанка",
    emoji: "🦋",
    targetMuscles: ["Большие грудные мышцы", "Передняя дельта"],
    defaultMet: 5.0,
    intensityFactor: 1.0,
    defaultSets: 3,
    defaultReps: 12,
    defaultWeightKg: 20,
    description: "Формирует красивую линию декольте и укрепляет связки плечевого пояса.",
    techniqueTip: "Держите локти чуть ниже плеч, плавно сводите рукояти перед грудью.",
  },
  {
    id: "cable_tricep_pushdown",
    name: "Разгибание рук на трицепс на блоке",
    nameEn: "Cable Tricep Pushdown",
    category: "back_upper",
    categoryLabel: "Руки и тонус",
    emoji: "💪",
    targetMuscles: ["Трицепс"],
    defaultMet: 4.5,
    intensityFactor: 0.9,
    defaultSets: 3,
    defaultReps: 15,
    defaultWeightKg: 15,
    description: "Убирает дряблость на задней поверхности рук, делая руки подтянутыми и изящными.",
    techniqueTip: "Прижмите локти к корпусу и не двигайте ими вперед-назад во время движения.",
  },
];
